-- Postgres counterpart to migrations/900_add_arr_seed.sql.
--
-- Type choices differ from the SQLite file on purpose:
--   * booleans are INTEGER 0/1, matching the rest of this schema and the Go
--     layer, which scans them into int and compares them with "= 1".
--   * file_size is BIGINT: Postgres INTEGER is int4 and caps at ~2 GB, while
--     SQLite INTEGER is variable width. Same reason as 064_widen_size_and_expiry_types.
--   * arr_seed_items.id and arr_seed_runs.id are BIGINT identity. Items are
--     re-upserted on every scan and Postgres evaluates nextval before conflict
--     detection, so the sequence burns even though the table stays small
--     (see 079_widen_int4_ids_to_bigint for the same failure mode).

-- Global settings (singleton, id=1)
CREATE TABLE arr_seed_settings (
    id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    enabled INTEGER NOT NULL DEFAULT 0,
    search_delay_seconds INTEGER NOT NULL DEFAULT 5,
    max_items_per_run INTEGER NOT NULL DEFAULT 0,
    enable_high_score_only INTEGER NOT NULL DEFAULT 0,
    enable_episode INTEGER NOT NULL DEFAULT 0,
    enable_season_pack_upgrade INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Per-ARR-instance cross-seed configuration
CREATE TABLE arr_seed_instance_configs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arr_instance_id INTEGER NOT NULL REFERENCES arr_instances(id) ON DELETE CASCADE,
    enabled INTEGER NOT NULL DEFAULT 1,
    target_qbit_instance_id INTEGER NOT NULL,
    category TEXT NOT NULL DEFAULT '',
    arr_docker_path TEXT NOT NULL DEFAULT '',
    host_data_path TEXT NOT NULL DEFAULT '',
    torrent_save_path TEXT NOT NULL DEFAULT '',
    scan_interval_minutes INTEGER NOT NULL DEFAULT 1440,
    unmonitor_after_seed INTEGER NOT NULL DEFAULT 0,
    tag_after_seed TEXT NOT NULL DEFAULT '',
    last_scan_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(arr_instance_id)
);

-- Scan run history
CREATE TABLE arr_seed_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id INTEGER NOT NULL REFERENCES arr_seed_instance_configs(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'running',
    triggered_by TEXT NOT NULL DEFAULT 'manual',
    items_scanned INTEGER NOT NULL DEFAULT 0,
    items_searched INTEGER NOT NULL DEFAULT 0,
    matches_found INTEGER NOT NULL DEFAULT 0,
    torrents_added INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);

-- Per-media-item tracking (dedup + history)
CREATE TABLE arr_seed_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id INTEGER NOT NULL REFERENCES arr_seed_instance_configs(id) ON DELETE CASCADE,
    item_type TEXT NOT NULL,
    arr_file_id INTEGER NOT NULL,
    release_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 3,
    status TEXT NOT NULL DEFAULT 'pending',
    torrent_hash TEXT,
    indexer_name TEXT,
    error_message TEXT,
    last_searched_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(config_id, item_type, arr_file_id)
);

CREATE INDEX idx_arr_seed_items_config_status
    ON arr_seed_items(config_id, status);
CREATE INDEX idx_arr_seed_runs_config
    ON arr_seed_runs(config_id);

-- Add ARR seed tags to cross-seed settings
ALTER TABLE cross_seed_settings ADD COLUMN arr_seed_tags TEXT NOT NULL DEFAULT '["cross-seed"]';
